unpack, vm: added arch packages unpacking, added install command description, fixed some bugs

diff --git a/scripts/sh/unpack b/scripts/sh/unpack
--- a/scripts/sh/unpack
+++ b/scripts/sh/unpack
@@ -18,6 +18,7 @@
 
 _VKDBG_DEBUG_RPM_DIR="debug-rpm"
 _VKDBG_DEBUG_DEB_DIR="debug-deb"
+_VKDBG_DEBUG_DEB_DIR="debug-pkg"
 
 _link_kernels_data() {
     mkdir -p versions
@@ -27,7 +28,7 @@ _link_kernels_data() {
     (
         cd "$target_machine_dir" || exit 1
 
-        for vmlinux_path in $(find root -type f | grep vmlinux$); do
+        for vmlinux_path in $(find root -type f | grep -e "vmlinux$\|vmlinuz$"); do
             version=$(echo "$vmlinux_path" | xargs dirname | xargs basename -a)
             kernel_link_name="kernel-$version"
             log_info "Found kernel at $vmlinux_path, version: $version"
@@ -125,6 +126,38 @@ _unpack_debug_deb() {
     return 0
 }
 
+_unpack_debug_pkg() {
+    local dep_err=false
+
+    check_vkdbg_additional_deps tar
+    dep_err=$(($? | $dep_err))
+
+    if [[ $dep_err -eq 1 ]]; then
+        log_error "Error unpacking pkg. Not all dependencies satisfied"
+        return 1
+    fi
+
+    target_directory=$1
+    mkdir -p "$target_directory/root"
+    log_info "Copying debs"
+    cp "$target_directory/$_VKDBG_DEBUG_DEB_DIR"/* "$target_directory/root"
+    (
+        cd "$target_directory/root" || exit 1
+        ar_executable=$(which ar)
+        tar_executable=$(which tar)
+
+        log_info "Installing debug sources and packages"
+        for filename in "$target_machine_dir"/root/*.zst; do
+            log_info "Processing $filename"
+            $tar_executable -I zstd -xvf "$filename"
+        done
+
+        rm "$target_machine_dir"/root/*.zst
+    )
+
+    return 0
+}
+
 check_and_prepare_vkdbg_sources() {
     local target_machine=$1
     local target_machine_dir
@@ -134,14 +167,17 @@ check_and_prepare_vkdbg_sources() {
 
     if [[ -d "$target_machine_dir/$_VKDBG_DEBUG_RPM_DIR" ]]; then
         log_info "Found debug rpm directory"
-         _unpack_debug_rpm "$target_machine_dir"
-         error=$?
+        _unpack_debug_rpm "$target_machine_dir"
+        error=$?
+    elif [[ -d "$target_machine_dir/$_VKDBG_DEBUG_PKG_DIR" ]]; then
+        log_info "Found debug pkg directory"
+        _unpack_debug_pkg "$target_machine_dir"
+        error=$?
     elif [[ -d "$target_machine_dir/$_VKDBG_DEBUG_DEB_DIR" ]]; then
         log_info "Found debug deb directory"
-         _unpack_debug_deb "$target_machine_dir"
-         error=$?
+        _unpack_debug_deb "$target_machine_dir"
+        error=$?
     fi
-
 
     if [[ $error != 0 ]]; then
         log_error "Error occurred while unpacking, please"
diff --git a/scripts/sh/vm b/scripts/sh/vm
--- a/scripts/sh/vm
+++ b/scripts/sh/vm
@@ -118,11 +118,10 @@ _vkdbg_vm_init() {
             assert_empty "$server_user" "Please specify remote user (--user | -u)"
             _vkdbg_vm_pull_remote "$server_user@$server_addr" "$path" "$target_machine_dir" "$server_key"
         elif [[ $use_cached == true ]]; then
-            pass
+            log_info "Starting..."
         else
             assert_empty "$path" "Please, specify path to bundle"
-            if [ ! -f "$target_machine_dir/bundle.tar.gz" ] || [ "$path" -nt "$target_machine_dir/bundle.tar.gz" ]
-            then
+            if [ ! -f "$target_machine_dir/bundle.tar.gz" ] || [ "$path" -nt "$target_machine_dir/bundle.tar.gz" ]; then
                 cp "$path" "$target_machine_dir/bundle.tar.gz"
             fi
         fi
@@ -146,38 +145,73 @@ _vkdbg_vm_init() {
 
         check_vkdbg_vm_env "$target_machine"
 
-        log_info "If your VM doesn't not exists yet, create it using image from bundle or using"
-        log_continue "or already unpacked image at $target_machine_dir/image.qcow2 and name it $target_machine"
-        log_continue "After (or, if machine already existed) add xmd scheme below to it's configuration"
-        log_continue "via virsh or virt-manager (read more there: https://access.redhat.com/blogs/766093/posts/2690881)"
-        log_continue "<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>"
-        log_continue "    <qemu:commandline>"
-        log_continue "        <qemu:arg value='-s'/>"
-        log_continue "    </qemu:commandline>"
-        log_continue "in the machine xml configuration (virsh)"
-        log_continue "You can also use bundled install script to set up and create machine (if it does not exist already): vkdbg vm install $target_machine "
+        _vkdbg_vm_install "$target_machine"
+        error=$?
+
+        if [[ error -eq 0 ]]; then
+            exit 0
+        else
+            log_info "If your VM doesn't not exists yet, create it using image from bundle or using"
+            log_continue "or already unpacked image at $target_machine_dir/image.qcow2 and name it $target_machine"
+            log_continue "After (or, if machine already existed) add xmd scheme below to it's configuration"
+            log_continue "via virsh or virt-manager (read more there: https://access.redhat.com/blogs/766093/posts/2690881)"
+            log_continue "<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>"
+            log_continue "    <qemu:commandline>"
+            log_continue "        <qemu:arg value='-s'/>"
+            log_continue "    </qemu:commandline>"
+            log_continue "in the machine xml configuration (virsh)"
+            log_continue "You can also use bundled install script to set up and create machine (if it does not exist already): vkdbg vm install $target_machine "
+        fi
+
+        log_info "Done"
     )
 }
 
-_vkdbg_vm_install(){
-    local target_machine=$1
+_vkdbg_vm_install_help() {
+    log_info "Install configuration for virt manager"
+    log_continue "$_VKDBG_NAME vm install <machine_name> [flags]"
+    log_continue "Available flags"
+    log_continue "    --help    | -h - show this message"
+    exit 0
+
+}
+
+_vkdbg_vm_install() {
+
+    local target_machine
+
+    while (("$#")); do
+        case "$1" in
+            --help | -h)
+                _vkdbg_vm_install_help
+                exit 0
+                ;;
+            --*)
+                _vkdbg_vm_install_help
+                exit 0
+                ;;
+            *)
+                target_machine=$1
+                ;;
+        esac
+        shift
+    done
 
     assert_empty "$target_machine" "Please, specify machine name"
-
     target_machine_dir="$(get_vkdbg_vm_directory "$target_machine")"
-
     assert_empty "$target_machine_dir" "Couldn't get directory machine directory"
-
     local meta_file_location="${target_machine_dir}/meta/config.xml"
 
-    if [ ! -f "$meta_file_location" ]
-    then
-        log_info "Cannot use bundled VM setup, the bundle did not provide a config in $target_machine_dir/meta/config.xml. You should execute virt-install manually"
-    exit 1
+    log_info "Installing configuration to virt-manager for ${target_machine}..."
+
+    if [ ! -f "$meta_file_location" ]; then
+        log_error "Cannot use bundled VM setup, the bundle did not provide a config in $target_machine_dir/meta/config.xml. You should execute virt-install manually"
+        exit 1
     fi
 
     sed -ie "s*DISK_PLACEHOLDER*${target_machine_dir}/image.qcow2*g" "${meta_file_location}"
-    sudo cp "$target_machine_dir"/meta/config.xml /etc/libvirt/qemu/"${target_machine}".xml || echo 'Could not place VM config to /etc/libvirt/qemu/"${target_machine}".xml'
+    elevated=$(check_privileges)
+    $elevated cp "$target_machine_dir"/meta/config.xml /etc/libvirt/qemu/"${target_machine}".xml
 }
 
 _vkdbg_vm_deinit() {
@@ -913,6 +947,7 @@ _vkdbg_vm_cmd_help() {
     log_continue "$_VKDBG_NAME vm <cmd> [flags]"
     log_continue "Available commands"
     log_continue "    init        - init debug env from existing bundle (see vm bundle --help)"
+    log_continue "    install     - install configuration for machine (see vm install --help)"
     log_continue "    deinit      - remove env"
     log_continue "    start       - start virtual machine"
     log_continue "    stop        - stop virtual machine"
