some fixes + add virt-manager config bundling

diff --git a/scripts/sh/vm b/scripts/sh/vm
--- a/scripts/sh/vm
+++ b/scripts/sh/vm
@@ -121,7 +121,10 @@ _vkdbg_vm_init() {
             pass
         else
             assert_empty "$path" "Please, specify path to bundle"
-            cp "$path" "$target_machine_dir/bundle.tar.gz"
+            if [ ! -f "$target_machine_dir/bundle.tar.gz" ] || [ "$path" -nt "$target_machine_dir/bundle.tar.gz" ]
+            then
+                cp "$path" "$target_machine_dir/bundle.tar.gz"
+            fi
         fi
 
         if [[ $use_cached == false ]]; then
@@ -152,7 +155,29 @@ _vkdbg_vm_init() {
         log_continue "        <qemu:arg value='-s'/>"
         log_continue "    </qemu:commandline>"
         log_continue "in the machine xml configuration (virsh)"
+        log_continue "You can also use bundled install script to set up and create machine (if it does not exist already): vkdbg vm install $target_machine "
     )
+}
+
+_vkdbg_vm_install(){
+    local target_machine=$1
+
+    assert_empty "$target_machine" "Please, specify machine name"
+
+    target_machine_dir="$(get_vkdbg_vm_directory "$target_machine")"
+
+    assert_empty "$target_machine_dir" "Couldn't get directory machine directory"
+
+    local meta_file_location="${target_machine_dir}/meta/config.xml"
+
+    if [ ! -f "$meta_file_location" ]
+    then
+        log_info "Cannot use bundled VM setup, the bundle did not provide a config in $target_machine_dir/meta/config.xml. You should execute virt-install manually"
+    exit 1
+    fi
+
+    sed -ie "s*DISK_PLACEHOLDER*${target_machine_dir}/image.qcow2*g" "${meta_file_location}"
+    sudo cp "$target_machine_dir"/meta/config.xml /etc/libvirt/qemu/"${target_machine}".xml || echo 'Could not place VM config to /etc/libvirt/qemu/"${target_machine}".xml'
 }
 
 _vkdbg_vm_deinit() {
@@ -946,6 +971,10 @@ vkdbg_vm_cmd() {
                 ;;
             info)
                 shift && _vkdbg_vm_info "$@"
+                exit 0
+                ;;
+            install)
+                shift && _vkdbg_vm_install "$@"
                 exit 0
                 ;;
             --help | -h)
